[build]
builder = "DOCKERFILE"
dockerfilePath = "backenddockerfile"

[deploy]
startCommand = "uvicorn app.main:app --host 0.0.0.0 --port 8000"
healthcheckPath = "/"
healthcheckPort = "8000"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[deploy.healthcheck]
path = "/"
port = "8000"
interval = "30s"
timeout = "10s"
retries = 3
startPeriod = "30s"

# 数据库配置
[env]
DATABASE_URL = "postgresql://postgres:VklXzDrDMygoJNZjzzSlNLMjmqKIPaYQ@postgres.railway.internal:5432/railway" 