[build]
builder = "DOCKERFILE"
dockerfilePath = "backenddockerfile"

[deploy]
healthcheckPath = "/health"
healthcheckPort = "8000"
healthcheckTimeout = 60
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[deploy.healthcheck]
path = "/health"
port = "8000"
interval = "15s"
timeout = "5s"
retries = 3
startPeriod = "60s"

# 数据库配置
[env]
DATABASE_URL = "postgresql://postgres:VklXzDrDMygoJNZjzzSlNLMjmqKIPaYQ@postgres.railway.internal:5432/railway" 