[build]
builder = "DOCKERFILE"
dockerfilePath = "backenddockerfile"

[deploy]
healthcheckPath = "/"
healthcheckPort = "8001"
healthcheckTimeout = 60
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[deploy.healthcheck]
path = "/"
port = "8001"
interval = "10s"
timeout = "5s"
retries = 3
startPeriod = "30s"

# 数据库配置
[env]
DATABASE_URL = "postgresql://postgres:VklXzDrDMygoJNZjzzSlNLMjmqKIPaYQ@postgres.railway.internal:5432/railway" 