[build]
builder = "DOCKERFILE"
dockerfilePath = "backenddockerfile"

[deploy]
startCommand = "gunicorn app.main:app --bind 0.0.0.0:8000 --workers 1 --worker-class uvicorn.workers.UvicornWorker --timeout 120 --graceful-timeout 30 --log-level debug --access-logfile - --error-logfile - --capture-output --enable-stdio-inheritance"
healthcheckPath = "/health"
healthcheckPort = 8000
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[deploy.healthcheck]
path = "/health"
port = 8000
interval = "20s"
timeout = "15s"
retries = 3
startPeriod = "90s"

# 环境变量配置
[env]
ENV = "production"
PYTHONPATH = "/app/backend"
PORT = "8000"
WORKERS = "1"
WORKER_CLASS = "uvicorn.workers.UvicornWorker"
LOG_LEVEL = "debug"
PYTHONUNBUFFERED = "1"
DATABASE_URL = "postgresql://postgres:VklXzDrDMygoJNZjzzSlNLMjmqKIPaYQ@postgres.railway.internal:5432/railway" 