[build]
builder = "DOCKERFILE"
dockerfilePath = "backenddockerfile"

[deploy]
startCommand = "gunicorn app.main:app --workers 2 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000 --timeout 120 --keep-alive 5 --log-level debug --access-logfile - --error-logfile - --capture-output"
healthcheckPath = "/health"
healthcheckPort = 8000
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5

[deploy.healthcheck]
path = "/health"
port = 8000
interval = "15s"
timeout = "30s"
retries = 5
startPeriod = "60s"

# 环境变量配置
[env]
ENV = "production"
PYTHONPATH = "/app/backend"
PORT = "8000"
DATABASE_URL = "postgresql://postgres:VklXzDrDMygoJNZjzzSlNLMjmqKIPaYQ@postgres.railway.internal:5432/railway" 