[build]
builder = "DOCKERFILE"
dockerfilePath = "backenddockerfile"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[deploy.healthcheck]
path = "/health"
interval = "30s"
timeout = "10s"
retries = 3
startPeriod = "60s"

# 数据库配置
[env]
DATABASE_URL = "postgresql://postgres:VklXzDrDMygoJNZjzzSlNLMjmqKIPaYQ@postgres.railway.internal:5432/railway" 