"""add ip_whitelist column

Revision ID: f091f46bf452
Revises: 
Create Date: 2025-02-21 19:41:26.909804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f091f46bf452'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ip_whitelist_id', table_name='ip_whitelist')
    op.drop_table('ip_whitelist')
    op.drop_index('ix_cities_city_code', table_name='cities')
    op.drop_index('ix_cities_id', table_name='cities')
    op.drop_table('cities')
    op.drop_index('ix_areas_area_code', table_name='areas')
    op.drop_index('ix_areas_id', table_name='areas')
    op.drop_table('areas')
    op.drop_index('ix_countries_country_code', table_name='countries')
    op.drop_index('ix_countries_id', table_name='countries')
    op.drop_table('countries')
    op.drop_index('ix_states_id', table_name='states')
    op.drop_index('ix_states_state_code', table_name='states')
    op.drop_table('states')
    op.add_column('product_inventory', sa.Column('ip_whitelist', sa.JSON(), nullable=True, comment='IP白名单列表'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_inventory', 'ip_whitelist')
    op.create_table('states',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('state_code', sa.VARCHAR(length=50), nullable=True),
    sa.Column('state_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('country_id', sa.INTEGER(), nullable=True),
    sa.Column('enable', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_states_state_code', 'states', ['state_code'], unique=False)
    op.create_index('ix_states_id', 'states', ['id'], unique=False)
    op.create_table('countries',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('country_code', sa.VARCHAR(length=50), nullable=True),
    sa.Column('country_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('area_id', sa.INTEGER(), nullable=True),
    sa.Column('enable', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_countries_id', 'countries', ['id'], unique=False)
    op.create_index('ix_countries_country_code', 'countries', ['country_code'], unique=1)
    op.create_table('areas',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('area_code', sa.VARCHAR(length=50), nullable=True),
    sa.Column('area_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('enable', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_areas_id', 'areas', ['id'], unique=False)
    op.create_index('ix_areas_area_code', 'areas', ['area_code'], unique=1)
    op.create_table('cities',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('city_code', sa.VARCHAR(length=50), nullable=True),
    sa.Column('city_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('country_id', sa.INTEGER(), nullable=True),
    sa.Column('enable', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cities_id', 'cities', ['id'], unique=False)
    op.create_index('ix_cities_city_code', 'cities', ['city_code'], unique=False)
    op.create_table('ip_whitelist',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('ip', sa.VARCHAR(length=50), nullable=False),
    sa.Column('product_no', sa.VARCHAR(length=50), nullable=False),
    sa.Column('proxy_type', sa.INTEGER(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ip_whitelist_id', 'ip_whitelist', ['id'], unique=False)
    # ### end Alembic commands ### 