"""initial migration

Revision ID: 290333ada430
Revises: 
Create Date: 2025-01-27 14:51:07.580092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '290333ada430'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_proxy_info_id', table_name='proxy_info')
    op.drop_table('proxy_info')
    op.drop_index('ix_instances_id', table_name='instances')
    op.drop_table('instances')
    op.drop_index('ix_resource_usage_id', table_name='resource_usage')
    op.drop_table('resource_usage')
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    op.create_table('resource_usage',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('resource_type', sa.VARCHAR(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('total', sa.INTEGER(), nullable=True),
    sa.Column('used', sa.INTEGER(), nullable=True),
    sa.Column('today', sa.INTEGER(), nullable=True),
    sa.Column('last_month', sa.INTEGER(), nullable=True),
    sa.Column('available', sa.INTEGER(), nullable=True),
    sa.Column('percentage', sa.FLOAT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_resource_usage_id', 'resource_usage', ['id'], unique=False)
    op.create_table('instances',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('ip_address', sa.VARCHAR(length=50), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_instances_id', 'instances', ['id'], unique=False)
    op.create_table('proxy_info',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('balance', sa.FLOAT(), nullable=True),
    sa.Column('total_recharge', sa.FLOAT(), nullable=True),
    sa.Column('total_consumption', sa.FLOAT(), nullable=True),
    sa.Column('month_recharge', sa.FLOAT(), nullable=True),
    sa.Column('month_consumption', sa.FLOAT(), nullable=True),
    sa.Column('last_month_consumption', sa.FLOAT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_proxy_info_id', 'proxy_info', ['id'], unique=False)
    # ### end Alembic commands ###
