"""add area tables

Revision ID: 537f7e1ef921
Revises: 
Create Date: 2025-02-19 22:27:18.649750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '537f7e1ef921'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('regions')
    op.drop_table('countries')
    op.drop_table('cities')
    op.drop_index('ix_product_inventory_product_no', table_name='product_inventory')
    op.create_index(op.f('ix_product_inventory_product_no'), 'product_inventory', ['product_no'], unique=True)
    op.create_index('ix_product_inventory_country_code', 'product_inventory', ['country_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_product_inventory_country_code', table_name='product_inventory')
    op.drop_index(op.f('ix_product_inventory_product_no'), table_name='product_inventory')
    op.create_index('ix_product_inventory_product_no', 'product_inventory', ['product_no'], unique=False)
    op.create_table('cities',
    sa.Column('code', sa.VARCHAR(length=50), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('country_code', sa.VARCHAR(length=50), nullable=True),
    sa.Column('status', sa.INTEGER(), nullable=True),
    sa.Column('last_sync_at', sa.DATETIME(), nullable=True),
    sa.Column('sync_status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('error_count', sa.INTEGER(), nullable=True),
    sa.Column('next_sync_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['country_code'], ['countries.code'], ),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('countries',
    sa.Column('code', sa.VARCHAR(length=50), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('region_code', sa.VARCHAR(length=50), nullable=True),
    sa.Column('status', sa.INTEGER(), nullable=True),
    sa.Column('last_sync_at', sa.DATETIME(), nullable=True),
    sa.Column('sync_status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('error_count', sa.INTEGER(), nullable=True),
    sa.Column('next_sync_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['region_code'], ['regions.code'], ),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('regions',
    sa.Column('code', sa.VARCHAR(length=50), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('status', sa.INTEGER(), nullable=True),
    sa.Column('last_sync_at', sa.DATETIME(), nullable=True),
    sa.Column('sync_status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('error_count', sa.INTEGER(), nullable=True),
    sa.Column('next_sync_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    # ### end Alembic commands ###
