"""initial migration

Revision ID: 630f9f031705
Revises: 
Create Date: 2025-01-23 16:13:43.385160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '630f9f031705'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_instances_app_username', table_name='instances')
    op.drop_index('ix_instances_id', table_name='instances')
    op.drop_index('ix_instances_instance_id', table_name='instances')
    op.drop_table('instances')
    op.drop_index('ix_proxy_info_id', table_name='proxy_info')
    op.drop_table('proxy_info')
    op.drop_index('ix_resource_usage_id', table_name='resource_usage')
    op.drop_table('resource_usage')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resource_usage',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('resource_type', sa.VARCHAR(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('total', sa.INTEGER(), nullable=True),
    sa.Column('used', sa.INTEGER(), nullable=True),
    sa.Column('today', sa.INTEGER(), nullable=True),
    sa.Column('last_month', sa.INTEGER(), nullable=True),
    sa.Column('available', sa.INTEGER(), nullable=True),
    sa.Column('percentage', sa.FLOAT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_resource_usage_id', 'resource_usage', ['id'], unique=False)
    op.create_table('proxy_info',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('balance', sa.FLOAT(), nullable=True),
    sa.Column('total_recharge', sa.FLOAT(), nullable=True),
    sa.Column('total_consumption', sa.FLOAT(), nullable=True),
    sa.Column('month_recharge', sa.FLOAT(), nullable=True),
    sa.Column('month_consumption', sa.FLOAT(), nullable=True),
    sa.Column('last_month_consumption', sa.FLOAT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_proxy_info_id', 'proxy_info', ['id'], unique=False)
    op.create_table('instances',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('instance_id', sa.VARCHAR(length=50), nullable=True),
    sa.Column('app_username', sa.VARCHAR(length=50), nullable=True),
    sa.Column('total_flow', sa.FLOAT(), nullable=True),
    sa.Column('used_flow', sa.FLOAT(), nullable=True),
    sa.Column('remaining_flow', sa.FLOAT(), nullable=True),
    sa.Column('month_flow', sa.FLOAT(), nullable=True),
    sa.Column('month_used', sa.FLOAT(), nullable=True),
    sa.Column('last_month_used', sa.FLOAT(), nullable=True),
    sa.Column('today_used', sa.FLOAT(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_instances_instance_id', 'instances', ['instance_id'], unique=1)
    op.create_index('ix_instances_id', 'instances', ['id'], unique=False)
    op.create_index('ix_instances_app_username', 'instances', ['app_username'], unique=False)
    # ### end Alembic commands ###
