"""update proxy info and resource usage models

Revision ID: 78439e32f7ce
Revises: 
Create Date: 2025-01-23 11:12:41.214577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78439e32f7ce'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_flow_usage_id', table_name='flow_usage')
    op.drop_table('flow_usage')
    op.drop_index('ix_agents_app_username', table_name='agents')
    op.drop_index('ix_agents_id', table_name='agents')
    op.drop_index('ix_agents_platform_account', table_name='agents')
    op.drop_table('agents')
    op.add_column('proxy_info', sa.Column('residential_balance', sa.Float(), nullable=True))
    op.add_column('proxy_info', sa.Column('datacenter_balance', sa.Float(), nullable=True))
    op.drop_column('proxy_info', 'balance')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proxy_info', sa.Column('balance', sa.FLOAT(), nullable=True))
    op.drop_column('proxy_info', 'datacenter_balance')
    op.drop_column('proxy_info', 'residential_balance')
    op.create_table('agents',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('app_username', sa.VARCHAR(length=32), nullable=True),
    sa.Column('platform_account', sa.VARCHAR(length=32), nullable=True),
    sa.Column('password', sa.VARCHAR(length=64), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('remark', sa.VARCHAR(length=255), nullable=True),
    sa.Column('balance', sa.FLOAT(), nullable=True),
    sa.Column('limit_flow', sa.INTEGER(), nullable=True),
    sa.Column('main_account', sa.VARCHAR(length=32), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['main_account'], ['main_users.app_username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agents_platform_account', 'agents', ['platform_account'], unique=1)
    op.create_index('ix_agents_id', 'agents', ['id'], unique=False)
    op.create_index('ix_agents_app_username', 'agents', ['app_username'], unique=1)
    op.create_table('flow_usage',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('monthly_usage', sa.FLOAT(), nullable=True),
    sa.Column('daily_usage', sa.FLOAT(), nullable=True),
    sa.Column('last_month_usage', sa.FLOAT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_flow_usage_id', 'flow_usage', ['id'], unique=False)
    # ### end Alembic commands ###
