"""add is_agent field to user model

Revision ID: add_is_agent_field
Revises: 03a3a29c450b
Create Date: 2025-01-29 02:36:07.869298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'add_is_agent_field'
down_revision: Union[str, None] = '03a3a29c450b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_agent', sa.Boolean(), nullable=True, default=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_agent')
    # ### end Alembic commands ### 