"""recreate_global_price_column

Revision ID: ee71b32b88f1
Revises: e6b45db80ea4
Create Date: 2025-02-12 17:54:01.169499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee71b32b88f1'
down_revision: Union[str, None] = 'e6b45db80ea4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proxy_info',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.Column('total_recharge', sa.Float(), nullable=True),
    sa.Column('total_consumption', sa.Float(), nullable=True),
    sa.Column('month_recharge', sa.Float(), nullable=True),
    sa.Column('month_consumption', sa.Float(), nullable=True),
    sa.Column('last_month_consumption', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resource_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('price', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_resource_types_id'), 'resource_types', ['id'], unique=False)
    op.create_table('resource_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource_type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.Column('used', sa.Integer(), nullable=True),
    sa.Column('today', sa.Integer(), nullable=True),
    sa.Column('last_month', sa.Integer(), nullable=True),
    sa.Column('available', sa.Integer(), nullable=True),
    sa.Column('percentage', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resource_usage_id'), 'resource_usage', ['id'], unique=False)
    op.create_table('agent_statistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('total_users', sa.Integer(), nullable=False),
    sa.Column('active_users', sa.Integer(), nullable=False),
    sa.Column('total_orders', sa.Integer(), nullable=False),
    sa.Column('active_orders', sa.Integer(), nullable=False),
    sa.Column('total_consumption', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('monthly_consumption', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('dynamic_resource_count', sa.Integer(), nullable=False),
    sa.Column('static_resource_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_statistics_id'), 'agent_statistics', ['id'], unique=False)
    op.create_table('resource_usage_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('resource_type_id', sa.Integer(), nullable=True),
    sa.Column('usage_amount', sa.Float(), nullable=True),
    sa.Column('usage_type', sa.String(length=50), nullable=True),
    sa.Column('remark', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['resource_type_id'], ['resource_types.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resource_usage_statistics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('resource_type_id', sa.Integer(), nullable=True),
    sa.Column('total_openings', sa.Integer(), nullable=True),
    sa.Column('monthly_openings', sa.Integer(), nullable=True),
    sa.Column('available_count', sa.Integer(), nullable=True),
    sa.Column('expired_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['resource_type_id'], ['resource_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('agent_prices', 'dynamic_proxy_price',
               existing_type=sa.DECIMAL(precision=10, scale=4),
               type_=sa.Numeric(precision=10, scale=2),
               nullable=True)
    op.alter_column('agent_prices', 'static_proxy_price',
               existing_type=sa.DECIMAL(precision=10, scale=4),
               type_=sa.Numeric(precision=10, scale=2),
               nullable=True)
    op.alter_column('agent_prices', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('agent_prices', 'updated_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.create_index(op.f('ix_agent_prices_id'), 'agent_prices', ['id'], unique=False)
    op.alter_column('dynamic_orders', 'order_no',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('dynamic_orders', 'app_order_no',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_index('ix_dynamic_orders_agent_id', table_name='dynamic_orders')
    op.drop_index('ix_dynamic_orders_status', table_name='dynamic_orders')
    op.drop_index('ix_dynamic_orders_user_id', table_name='dynamic_orders')
    op.create_index(op.f('ix_dynamic_orders_id'), 'dynamic_orders', ['id'], unique=False)
    op.alter_column('flow_usage', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=False)
    op.alter_column('flow_usage', 'updated_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=False)
    op.alter_column('instances', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=False)
    op.alter_column('instances', 'updated_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=False)
    op.drop_index('ix_instances_status', table_name='instances')
    op.drop_index('ix_instances_instance_no', table_name='instances')
    op.create_index(op.f('ix_instances_instance_no'), 'instances', ['instance_no'], unique=True)
    op.create_index(op.f('ix_product_inventory_area_code'), 'product_inventory', ['area_code'], unique=False)
    op.create_index(op.f('ix_product_inventory_supplier_code'), 'product_inventory', ['supplier_code'], unique=False)
    op.alter_column('static_orders', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=False)
    op.alter_column('static_orders', 'updated_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=False)
    op.drop_index('ix_static_orders_order_no', table_name='static_orders')
    op.create_index(op.f('ix_static_orders_order_no'), 'static_orders', ['order_no'], unique=True)
    op.create_index(op.f('ix_static_orders_app_order_no'), 'static_orders', ['app_order_no'], unique=False)
    op.create_index(op.f('ix_static_orders_city_code'), 'static_orders', ['city_code'], unique=False)
    op.create_index(op.f('ix_static_orders_country_code'), 'static_orders', ['country_code'], unique=False)
    op.create_index(op.f('ix_static_orders_product_no'), 'static_orders', ['product_no'], unique=False)
    op.create_index(op.f('ix_static_orders_proxy_type'), 'static_orders', ['proxy_type'], unique=False)
    op.create_index(op.f('ix_static_orders_region_code'), 'static_orders', ['region_code'], unique=False)
    op.create_index(op.f('ix_static_orders_static_type'), 'static_orders', ['static_type'], unique=False)
    op.alter_column('transactions', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=False)
    op.alter_column('transactions', 'updated_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=False)
    op.drop_index('ix_transactions_transaction_no', table_name='transactions')
    op.create_index(op.f('ix_transactions_transaction_no'), 'transactions', ['transaction_no'], unique=True)
    op.alter_column('users', 'last_login_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('users', 'updated_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.drop_index('ix_users_agent_id', table_name='users')
    op.drop_index('ix_users_username', table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index('ix_users_username', 'users', ['username'], unique=False)
    op.create_index('ix_users_agent_id', 'users', ['agent_id'], unique=False)
    op.alter_column('users', 'updated_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('users', 'last_login_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
    op.drop_index(op.f('ix_transactions_transaction_no'), table_name='transactions')
    op.create_index('ix_transactions_transaction_no', 'transactions', ['transaction_no'], unique=False)
    op.alter_column('transactions', 'updated_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               nullable=True)
    op.alter_column('transactions', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               nullable=True)
    op.drop_index(op.f('ix_static_orders_static_type'), table_name='static_orders')
    op.drop_index(op.f('ix_static_orders_region_code'), table_name='static_orders')
    op.drop_index(op.f('ix_static_orders_proxy_type'), table_name='static_orders')
    op.drop_index(op.f('ix_static_orders_product_no'), table_name='static_orders')
    op.drop_index(op.f('ix_static_orders_country_code'), table_name='static_orders')
    op.drop_index(op.f('ix_static_orders_city_code'), table_name='static_orders')
    op.drop_index(op.f('ix_static_orders_app_order_no'), table_name='static_orders')
    op.drop_index(op.f('ix_static_orders_order_no'), table_name='static_orders')
    op.create_index('ix_static_orders_order_no', 'static_orders', ['order_no'], unique=False)
    op.alter_column('static_orders', 'updated_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               nullable=True)
    op.alter_column('static_orders', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               nullable=True)
    op.drop_index(op.f('ix_product_inventory_supplier_code'), table_name='product_inventory')
    op.drop_index(op.f('ix_product_inventory_area_code'), table_name='product_inventory')
    op.drop_index(op.f('ix_instances_instance_no'), table_name='instances')
    op.create_index('ix_instances_instance_no', 'instances', ['instance_no'], unique=False)
    op.create_index('ix_instances_status', 'instances', ['status'], unique=False)
    op.alter_column('instances', 'updated_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               nullable=True)
    op.alter_column('instances', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               nullable=True)
    op.alter_column('flow_usage', 'updated_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               nullable=True)
    op.alter_column('flow_usage', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               nullable=True)
    op.drop_index(op.f('ix_dynamic_orders_id'), table_name='dynamic_orders')
    op.create_index('ix_dynamic_orders_user_id', 'dynamic_orders', ['user_id'], unique=False)
    op.create_index('ix_dynamic_orders_status', 'dynamic_orders', ['status'], unique=False)
    op.create_index('ix_dynamic_orders_agent_id', 'dynamic_orders', ['agent_id'], unique=False)
    op.alter_column('dynamic_orders', 'app_order_no',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('dynamic_orders', 'order_no',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_index(op.f('ix_agent_prices_id'), table_name='agent_prices')
    op.alter_column('agent_prices', 'updated_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('agent_prices', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('agent_prices', 'static_proxy_price',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DECIMAL(precision=10, scale=4),
               nullable=False)
    op.alter_column('agent_prices', 'dynamic_proxy_price',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DECIMAL(precision=10, scale=4),
               nullable=False)
    op.drop_table('resource_usage_statistics')
    op.drop_table('resource_usage_history')
    op.drop_index(op.f('ix_agent_statistics_id'), table_name='agent_statistics')
    op.drop_table('agent_statistics')
    op.drop_index(op.f('ix_resource_usage_id'), table_name='resource_usage')
    op.drop_table('resource_usage')
    op.drop_index(op.f('ix_resource_types_id'), table_name='resource_types')
    op.drop_table('resource_types')
    op.drop_table('proxy_info')
    # ### end Alembic commands ###
